name: Validate Docker Compose

on:
  push:
    branches:
      - main
    paths:
      - 'docker-compose.yml'
      - '.github/workflows/validate-compose.yml'

jobs:
  validate-docker-compose:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Docker Compose
        uses: ndeloof/install-compose-action@v0.0.1

      - name: Validate Docker Compose configuration
        run: docker-compose config --no-interpolate
